version: '3'
services: 
  #nginx:
   # build:
# Nester Service
  nester-uno:
    build: .
    hostname: nester
    ports:
      - "127.0.0.1:5000:5000"
# Service de monitoring 
  monitoring:
    image: portainer/portainer-ce:latest
    ports:
      - "127.0.0.1:9443:9443"
    volumes:
        - ./portainer:/data
        - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus:/etc/prometheus
    ports:
      - "127.0.0.1:9090:9090"

  grafana:
    image: grafana/grafana
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=#ASRBD@ 
    ports:
      - "127.0.0.1:3000:3000"

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    #ports:
    #- 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /etc/machine-id:/etc/machine-id:ro
    - /var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro
